### ISSUE TITLE
Cannot be used __without__ rom

### ISSUE THREAD

**Issue by kwando** [rom-rb/rom-model#3]
rom-model depends on rom, or more specifically the rom/constants file which exists in `rom` gem.

**Comment by solnic** [comment]
Which ones?

**Comment by d-Pixie** [comment]
If you follow the example in `lib/rom/model/attributes.rb` and try to use `rom-model` by mixing in `ROM::Model::Attributes` you get this error:

```
/Users/pixie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-model-0.2.0/lib/rom/model/validator.rb:5:in `require': cannot load such file -- rom/constants (LoadError)
from /Users/pixie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-model-0.2.0/lib/rom/model/validator.rb:5:in `<top (required)>'
from /Users/pixie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-model-0.2.0/lib/rom/model.rb:2:in `require'
from /Users/pixie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-model-0.2.0/lib/rom/model.rb:2:in `<top (required)>'
from /Users/pixie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-model-0.2.0/lib/rom-model.rb:1:in `require'
from /Users/pixie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-model-0.2.0/lib/rom-model.rb:1:in `<top (required)>'
from /Users/pixie/projects/fortnox-api/lib/fortnox/api/models/invoice.rb:5:in `require'
    ...
```

The project at this point only includes `rom-model` not the `rom` gem.

Either make the dependency explicit by adding the `rom` gem as a dep. to `rom-model` or, better for standalone use, remove the dependency or refactor it out into something a bit more lightweight to include than `rom` :)

**Comment by d-Pixie** [comment]
@solnic ping me if you need any further info.

**Comment by solnic** [comment]
Seems like we're missing `require "rom/constants"` which is actually provided by `rom-support` which this gem does depend on.

**Comment by d-Pixie** [comment]
Also given that I get the following errors when adding `rom` as a dependency to the project to solve the above error:

```
/Users/pixie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-0.8.1/lib/rom/constants.rb:3: warning: already initialized constant ROM::Undefined
/Users/pixie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-support-1.0.0/lib/rom/support/constants.rb:2: warning: previous definition of Undefined was here
/Users/pixie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-0.8.1/lib/rom/constants.rb:41: warning: already initialized constant ROM::EMPTY_ARRAY
/Users/pixie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-support-1.0.0/lib/rom/support/constants.rb:4: warning: previous definition of EMPTY_ARRAY was here
/Users/pixie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-0.8.1/lib/rom/constants.rb:42: warning: already initialized constant ROM::EMPTY_HASH
/Users/pixie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-support-1.0.0/lib/rom/support/constants.rb:3: warning: previous definition of EMPTY_HASH was here
```

I think the errors is as simple as that the `require 'rom/constants'` line in `lib/rom/model/validator.rb:5` should really be `require 'rom-support/constants'` instead.

**Comment by solnic** [comment]
Sorry, I meant `require "rom/support/constants"`.

**Comment by d-Pixie** [comment]
Ah, well, path smath :) Want a PR or will you fix it?

**Comment by solnic** [comment]
PR would be awesome :)

**Comment by solnic** [comment]
btw: https://github.com/rom-rb/rom-model/blob/master/README.md#future-plans

**Comment by d-Pixie** [comment]
@solnic while fixing the above error I get the same problem a few lines further down for `require 'rom/pipeline'` that is used when creating the `Pipeline` class. This seem to actually be in the `rom` gem :/

How would you want me to handle that? One choice is to migrate that out into the support gem as well, but that is a series of PRs in that case.

**Comment by d-Pixie** [comment]
Ah, just read the future plans section. Might not be worth fixing then :) I'll have a look at the suggested replacements instead.

**Comment by solnic** [comment]
Sorry for the confusion. This gem was extracted from rom-rails but I stopped using rails and anything with Active\* prefix, so I have no reason to maintain this one anymore :/ As mentioned in README, we _may_ need some sort of integration between dry-validation and rom, so _maybe_ rom-model would become that. We'll see.
